
name: docker-hub-publish
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run:  docker build . --tag rdok/gpp:alpine3.12
    - name: Test
      run:  |
        ouput=$(docker run --rm -i rdok/gpp:alpine3.12 --version)
        if [[ $output != *"g++ (Alpine"* ]]; then
          echo "Expected g++ identifier was not found."
          exit 1
        fi
    - name: Docker login
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push image
      run:  docker image push rdok/gpp
    - name: Docker logout
      run: docker logout

