
name: docker-hub-publish
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run:  docker build . --tag rdok/gpp:alpine3.12
    - name: Docker login
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push image
      run:  docker image push rdok/gpp
    - name: Docker logout
      run: docker logout

